ALTER TABLE country_stats ADD COLUMN commands INTEGER NOT NULL DEFAULT 0;
ALTER TABLE country_stats ADD COLUMN raw_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE country_stats ADD COLUMN emitted_bytes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE program_stats ADD COLUMN raw_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE program_stats ADD COLUMN emitted_bytes INTEGER NOT NULL DEFAULT 0;

ALTER TABLE country_program_stats ADD COLUMN raw_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE country_program_stats ADD COLUMN emitted_bytes INTEGER NOT NULL DEFAULT 0;
